export const TEACHERS = [
	{
		id: 1,
		name: 'Картвелишвили ТАТЬЯНА',
		role: 'Соруководитель Школы, преподаватель математики, физики',
		imageSrc: './images/teachers/kartvelishvili_tatyana.png',
		placeholderSrc: './images/teachers/kartvelishvili_tatyana.png',
	},
	{
		id: 2,
		name: 'Зизганова ЕЛЕНА',
		role: 'Преподаватель математики, методист',
		imageSrc: './images/teachers/zizganova_elena.png',
		placeholderSrc: './images/teachers/zizganova_elena.png',
	},
	{
		id: 3,
		name: 'Кораблинов НИКИТА',
		role: 'Преподаватель программирования, дизайнер',
		imageSrc: './images/teachers/korablinov_nikita.png',
		placeholderSrc: './images/teachers/korablinov_nikita.png',
	},
	{
		id: 4,
		name: 'Волкова АЛЕКСАНДРА',
		role: 'Администратор, преподаватель математики',
		imageSrc: './images/teachers/volkova_aleksandra.png',
		placeholderSrc: './images/teachers/volkova_aleksandra.png',
	},
	{
		id: 5,
		name: 'Хмелёва КСЕНИЯ',
		role: 'Преподаватель русского языка, преподаватель классов "Математическая вертикаль", филолог',
		imageSrc: './images/teachers/hmeleva_kseniya.png',
		placeholderSrc: './images/teachers/hmeleva_kseniya.png',
	},
	{
		id: 6,
		name: 'Розанов АРТЁМ',
		role: 'Преподаватель физики',
		imageSrc: './images/teachers/rozanov_artem.png',
		placeholderSrc: './images/teachers/rozanov_artem.png',
	},
	{
		id: 7,
		name: 'Шарафетдинов ЕГОР',
		role: 'Преподаватель математики',
		imageSrc: './images/teachers/sharafetdinov_egor.png',
		placeholderSrc: './images/teachers/sharafetdinov_egor.png',
	},
	{
		id: 8,
		name: 'Шимбирёв СЕРГЕЙ',
		role: 'Преподаватель математики',
		imageSrc: './images/teachers/shimbirev_sergey.png',
		placeholderSrc: './images/teachers/shimbirev_sergey.png',
	},
	{
		id: 9,
		name: 'Шеремет ДАНИИЛ',
		role: 'Преподаватель математики',
		imageSrc: './images/teachers/sheremet_daniil.png',
		placeholderSrc: './images/teachers/sheremet_daniil.png',
	},
	{
		id: 10,
		name: 'Матвеев АЛЕКСЕЙ',
		role: 'Преподаватель математики',
		imageSrc: './images/teachers/matveev_aleksey.png',
		placeholderSrc: './images/teachers/matveev_aleksey.png',
	},
	{
		id: 11,
		name: 'Авдасев ОЛЕГ',
		role: 'Преподаватель математики',
		imageSrc: './images/teachers/avdasev_oleg.png',
		placeholderSrc: './images/teachers/avdasev_oleg.png',
	},
	{
		id: 12,
		name: 'Нойкин АЛЕКСЕЙ',
		role: 'Старший инженер',
		imageSrc: './images/teachers/noykin_aleksey.png',
		placeholderSrc: './images/teachers/noykin_aleksey.png',
	},
]
