export const TEACHERS = [
	{
		id: 1,
		name: 'ЮМАШЕВ Михаил Владиславович',
		role: 'Руководитель Школы Точных Наук',
		imageSrc: './images/teachers/photo1.jpeg',
		placeholderSrc: './images/teachers/tiny2.jpg',
	},
	{
		id: 2,
		name: 'КАРТВЕЛИШВИЛИ Татьяна',
		role: 'Соруководитель Школы, преподаватель математики',
		imageSrc: './images/teachers/photo2.jpeg',
		placeholderSrc: './images/teachers/tiny1.jpeg',
	},
	{
		id: 3,
		name: 'ЗИЗГАНОВА Елена',
		role: 'Преподаватель математики',
		imageSrc: './images/teachers/photo3.jpg',
		placeholderSrc: './images/teachers/tiny5.jpg',
	},
	{
		id: 4,
		name: 'ХМЕЛЕВА Ксения',
		role: 'Преподаватель русского языка',
		imageSrc: './images/teachers/photo5.jpg',
		placeholderSrc: './images/teachers/tiny7.jpg',
	},
	{
		id: 5,
		name: 'МАТВЕЕВ Алексей',
		role: 'Преподаватель математики',
		imageSrc: './images/teachers/photo6.jpg',
		placeholderSrc: './images/teachers/tiny8.jpg',
	},
	{
		id: 6,
		name: 'ВОЛКОВА Александра',
		role: 'Психолог-педагог, вожатый',
		imageSrc: './images/teachers/photo2.jpg',
		placeholderSrc: './images/teachers/tiny3.jpg',
	},
	{
		id: 7,
		name: 'КОРАБЛИНОВ Никита',
		role: 'Преподаватель программирования',
		imageSrc: './images/teachers/photo7.jpg',
		placeholderSrc: './images/teachers/tiny9.jpg',
	},
	{
		id: 8,
		name: 'НАЗАРОВ Артём',
		role: 'Преподаватель математики',
		imageSrc: './images/teachers/artem.webp',
		placeholderSrc: './images/teachers/artem_stub.webp',
	},
	{
		id: 9,
		name: 'ШУБИНА Александра',
		role: 'Преподаватель математики',
		imageSrc: './images/teachers/shubina_aleksandra.webp',
		placeholderSrc: './images/teachers/shubina_aleksandra_stub.webp',
	},
	{
		id: 10,
		name: 'АФАНАСЬЕВ Илья',
		role: 'Преподаватель математики',
		imageSrc: './images/teachers/afanasyev_ilya.webp',
		placeholderSrc: './images/teachers/afanasyev_ilya_placeholder.webp',
	},
]
